name = "workers-airtable-form"
main = "index.js"
compatibility_date = "2023-06-13"

[vars]
AIRTABLE_BASE_ID = "appeSWNykwi3SMV4O"
AIRTABLE_TABLE_NAME = "Form Submissions"
FORM_URL = "https://workers-airtable-form.pages.dev"
