name = "workers-airtable-form"
main = "src/index.js"
compatibility_date = "2023-05-09"

[vars]
AIRTABLE_BASE_ID = "appuKpifoMps5gP3q"
AIRTABLE_TABLE_NAME = "Form Submissions"
FORM_URL = "https://workers-airtable-form.pages.dev"
