name = "airtable-form-handler"
type = "javascript"

account_id = "34f1dce6cf7b9a3168128e86c514ae12"
workers_dev = true

[vars]
AIRTABLE_BASE_ID = "appf30jPzSGTyBIiJ"
AIRTABLE_TABLE_NAME = "Form Submissions"
FORM_URL = "https://workers-airtable-form.pages.dev"
